version: '3.7'

services:
  dbmysql:
    container_name: dbmysql
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'  
    volumes: 
      - ./sqlscript_seed.sql:/docker-entrypoint-initdb.d/script.sql
  app:
    container_name: appnode
    #restart: always
    depends_on:
      - dbmysql 
    build: app/
    env_file:
      - .env   
    ports:
      - 443:3000
    volumes:
      - ./app/src:/home/node/app/src/
      
    
